version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  rabbitmq-server:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data

  rest-server:
    build: ./rest-server
    container_name: rest-server
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/  # Adjust MongoDB URI as per your setup

  rest-client:
    build: ./rest-client
    container_name: rest-client
    ports:
      - "5001:5001"
    depends_on:
      - rest-server

volumes:
  mongo_data:
  rabbitmq_data:
