version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data

  rest-server:
    build: ./docker_services/rest/rest_server
    container_name: rest-server
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/  # Adjust MongoDB URI as per your setup

  rest-client:
    build: ./docker_services/rest/rest_client
    container_name: rest-client
    ports:
      - "5001:5001"
    depends_on:
      - rest-server
    environment:
      REST_SERVER_URL: http://rest-server:5000
  
  rabbitmq-server:
    build: ./docker_services/rabbitmq/rabbitmq_server
    container_name: rabbitmq-server
    ports:
      - "5010:5010"
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/
      RABBITMQ: rabbitmq
    depends_on:
      - rabbitmq
  
  rabbitmq-client:
    build: ./docker_services/rabbitmq/rabbitmq_client
    container_name: rabbitmq-client
    ports:
      - "5011:5011"
    depends_on:
      - rabbitmq-server
    environment:
      RABBIT_SERVER_URL: http://rabbitmq-server:5010/message

  grpc-server:
    build: ./docker_services/grpc/grpc_server
    container_name: grpc-server
    ports:
      - "5020:5020"
      - "5031:5031"
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/

  grpc-client:
    build: ./docker_services/grpc/grpc_client
    container_name: grpc-client
    ports:
      - "5021:5021"
    depends_on:
      - grpc-server
    environment:
      INSECURE_CHANNEL_NAME: grpc-server

  websocket-client:
    build: ./docker_services/websocket_client
    container_name: websocket-client
    ports:
      - "6000:6000"
    depends_on:
      - grpc-server
      - rabbitmq-server
      - rest-server
    environment:
      GRPC_SERVER_URL: http://grpc-server:5031
      RABBITMQ_SERVER_URL: http://rabbitmq-server:5010
      REST_SERVER_URL: http://rest-server:5000


volumes:
  mongo_data:
  rabbitmq_data:
